version: '3.7'

services:
  generic:
    build:
      context: .docker
      dockerfile: Dockerfile.dev
    volumes:
      - ./proto:/app
    working_dir: /app

  node_1:
    build:
      context: .docker
      dockerfile: Dockerfile.dev
    volumes:
      - ./microservices/micr1:/app
      - ./proto:/proto
    command: nest start --watch
    working_dir: /app

  node_2:
    build:
      context: .docker
      dockerfile: Dockerfile.dev
    volumes:
      - ./microservices/micr2:/app
      - ./proto:/proto
    command: nest start --watch
    working_dir: /app

  node_prisma:
    build:
      context: .docker
      dockerfile: Dockerfile.dev
    volumes:
      - ./microservices/micr_prisma:/app
      - ./proto:/proto
    command: nest start --watch
    working_dir: /app

  prisma:
    image: prismagraphql/prisma:1.14
    restart: always
    ports:
    - 4466:4466
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
            migrations: true
    depends_on: 
      - mysql

  mysql:
    image: mysql:5.7
    volumes:
      - ./data/mysql:/var/lib/mysql  
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
      # MYSQL_DATABASE: mysql
      # MYSQL_USER: mysql
      # MYSQL_PASSWORD: mysql
    ports: 
      - 3307:3306
    
  node_client:
    build:
      context: .docker
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
      - ./proto:/proto
    command: nest start --watch
    working_dir: /app
    ports: 
      - 3000:3000
    depends_on: 
      - node_1
      - node_2
      - node_prisma